version: '3.8'

services:

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootPW
      MYSQL_DATABASE: kaddem
      MYSQL_USER: youssef
      MYSQL_PASSWORD: youssef
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Define the volume for mySQL data
    networks:
      - kaddemNetwork

  kaddemBack:
    image: youssef06/alpine:2.0.0
    ports:
      - "8060:8060"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: youssef
      SPRING_DATASOURCE_PASSWORD: youssef
      SPRING_SERVER_PORT: 8089
    networks:
      - kaddemNetwork

networks:
  kaddemNetwork:

volumes:
  mysql_data:  # Define the named volume for PostgreSQL data