version: '3.8'

services:

  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
    networks:
      - newNetwork

  backend:
    image: backend
    ports:
      - "8888:8888"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.33.10:3306/kaddem\db?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_SERVER_PORT: 8888
    networks:
      - newNetwork

networks:
 newNetwork:

volumes:
 mysql_data:  
